### ISSUE TITLE
downstream break

### ISSUE THREAD

**Issue by mataddy** [TaddyLab/gamlr#13]
Hi @kkdey , in another project we found that the latest version of gamlr is dropping some of the (undocumented) arguments that we use to make it work with distrom.  We think it might be due to where, in your commit [here](https://github.com/TaddyLab/gamlr/commit/46e8be268e8e55fcaf3abf0014d22a5f042082b0#diff-ab2775c29226830637f3660742b89728L42) to gamlr.R you drop the elipses ... from the argument set.  Was there a reason to do that to make it OK for the latest R requirements?  Can we add them back in?

**Comment by mataddy** [comment]
Also @arosenbe is the observer who found the break and might be able to explain more.  Thanks both for all the help!

**Comment by kkdey** [comment]
I added back that change. I was mainly correcting the build warnings and I think it slipped my mind that distrom depended on gamlr in its undocumented arguments. Sorry for breaking it, will be more careful in future. @arosenbe thanks. Please let me know if it is running okay now.

**Comment by arosenbe** [comment]
Thanks @kkdey! That seems to have done it. I really appreciate you making the fix so quickly!

**Comment by mataddy** [comment]
Thanks @kkdey.  No worries, it's great that you're getting gamlr up to date.  FYI if you feel like assuming maintainer status and putting a latest version up on Cran it would be greatly appreciated.
