### ISSUE TITLE
Bug in observation weights with intercept=F

### ISSUE THREAD

**Issue by kennyjoseph** [TaddyLab/gamlr#16]
Below is what I believe to be an issue and its cause:

If you call ```gamlr``` with ```intercept=F```, then observation weights are not used.  

This is because the check in the ```sse``` function in the C code (line 27) looks at the first element of the weight vector and checks to see if its 0. If it is, then no weights are used. Because a 0 intercept is added (I believe) when run with ```intercept=F```, this ends up leading to no weights being used.

Obviously this is easy enough to work around but it took some time to figure out what was going on so thought I'd note it.

**Comment by mataddy** [comment]
there is no intercept=F argument that I know of?  I'll close but lmk if there is something I'm missing.  We always use an intercept in gamlr for stability reasons.

**Comment by kennyjoseph** [comment]
Hey, sorry and thanks.  It took me typing ```obsweight''' (vs ```obsweights''') by accident to realize what the real issue was.
